name: Makefile CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: unit-tests
      run: make unit-tests

    - name: Docker Build
      run: make docker

    - name: integration-tests
      run: make integration-tests
